[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
databuf = "*"

frpc = { path = "../" }
frpc-transport = { path = "../lib/frpc-transport" }
frpc-codegen-client = { path = "../lib/frpc-codegen-client" }