[workspace]
members = ["codegen", "codegen-macro", "std-trait"]

[package]
name = "irpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["io-util"] }

codegen = { path = "./codegen" }
std-trait = { path = "./std-trait" }

# quinn = "0.9.3"
# rustls = "0.20.7"
