[workspace]
# members = ["frpc-macros", "frpc-message", "codegen"]

[package]
name = "frpc"
version = "0.0.1"
edition = "2021"

license = "Apache-2.0"
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/frpc.rs"
keywords = ["rpc"]
description = "Flash RPC framework"

[dependencies]
databuf = "0.3"

frpc-macros = { version = "0.0.1", path = "lib/frpc-macros" }
frpc-message = { version = "0.0.1", path = "lib/frpc-message", features = ["encode"] }

tokio = { version = "1", features = ["io-util"] }
async-trait = "0.1"

[dev-dependencies]
# libloading = "0.7.4"
tokio = { version = "1", features = ["macros", "rt"] }