[package]
name = "codegen"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
frpc-message = { path = "../frpc-message", features = ["decode"] }
# toml = { version = "0.7", default-features = false, features = ["parse"] }
