[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
databuf = "0.1"
std-trait = { path = "../std-trait" }
codegen-macro = { path = "../codegen-macro" }
serde = { version = "1.0", features = ["derive"] }