[package]
name = "irpc"
version = "0.1.0"
edition = "2021"

[dependencies]
bin-layout = "7.1"
tokio = { version = "1", features = ["full"] }

codegen = { path = "../codegen" }
std-trait = { path = "../std-trait" }