[package]
name = "irpc"
version = "0.1.0"
edition = "2021"

[dependencies]
bin-layout = "7"
tokio = { version = "1", features = ["full"] }

macros = { path = "../macros" }
typegen = { path = "../typegen" }