[package]
name = "frpc-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
frpc = { path = "../frpc" }
h2-plus = { git = "https://github.com/nurmohammed840/h2-plus" }
tokio = { version = "1", features = ["io-util", "net", "rt-multi-thread", "macros"] }